version: '3'

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    volumes:
      - ./adguard.yaml:/opt/adguardhome/adguard.yaml
      - ./work:/opt/adguardhome/work
      - ./certs:/opt/adguardhome/work/certs
      - ./filters:/opt/adguardhome/work/filters
      - ./blocklists:/opt/adguardhome/work/blocklists
      - ./parental:/opt/adguardhome/work/parental
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    restart: unless-stopped
